spring:
  datasource:
    user:
      jdbc-url: jdbc:mysql://123.56.20.222:3306/VR_user
      driver-class-name: com.mysql.cj.jdbc.Driver
      allowMultiQueries: true
      username: VR
      password: VR
    task:
      jdbc-url: jdbc:mysql://123.56.20.222:3306/VR_task
      driver-class-name: com.mysql.cj.jdbc.Driver
      allowMultiQueries: true
      username: VR
      password: VR
    report:
      jdbc-url: jdbc:mysql://123.56.20.222:3306/VR_report
      driver-class-name: com.mysql.cj.jdbc.Driver
      allowMultiQueries: true
      username: VR
      password: VR


#  profiles:
#    active: dev

server:
  port: 8000

#mybatis:
#  mapper-locations: classpath*:com


